# Workflow name
name: Vprofile CICD Workflow

# Trigger the workflow on pushes to the main or develop branches
on:
  push:
    branches: [ "main"]

  pull_request:
    branches: [ "main" ]

# Trigger the workflow on a schedule
# Every Monday to Friday at 2:10 pm
  workflow_dispatch:
  schedule:
    - cron: "10 14 * * 1-5"

# Permissions
permissions:
  contents: read

# Jobs
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Build the application
      - name: Maven Build
        run: mvn install

      # Upload the build artifact (WAR)
      - name: Upload Build Artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      # Notify if the build fails
      - name: Notify if Build Fails
        if: failure()
        run: echo " Build job failed! Please check logs."


  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      # Checkout code
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run tests on the main branch
      - name: Run tests on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test

      # Run Checkstyle on the main branch
      - name: Checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      # Skip unit tests and code analysis on other branches
      - name: Run tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests and code analysis"
